In [4]:
import tensorflow as tf    
  
#两个矩阵相乘  
x=tf.constant([[1.0,2.0,3.0],[1.0,2.0,3.0],[1.0,2.0,3.0]])    
y=tf.constant([[0,0,1.0],[0,0,1.0],[0,0,1.0]])  
#注意这里这里x,y要有相同的数据类型，不然就会因为数据类型不匹配而出错  
z=tf.multiply(x,y)  
  
#两个数相乘  
x1=tf.constant(1)  
y1=tf.constant(2)  
#注意这里这里x1,y1要有相同的数据类型，不然就会因为数据类型不匹配而出错  
z1=tf.multiply(x1,y1)  
  
#数和矩阵相乘  
x2=tf.constant([[1.0,2.0,3.0],[1.0,2.0,3.0],[1.0,2.0,3.0]])  
y2=tf.constant(2.0)  
#注意这里这里x1,y1要有相同的数据类型，不然就会因为数据类型不匹配而出错  
z2=tf.multiply(x2,y2)  
  
with tf.Session() as sess:    
    print(sess.run(z))  
    print(sess.run(z1))  
    print(sess.run(z2)) 

[[ 0.  0.  3.]
 [ 0.  0.  3.]
 [ 0.  0.  3.]]
2
[[ 2.  4.  6.]
 [ 2.  4.  6.]
 [ 2.  4.  6.]]


In [1]:
# -*- coding: utf-8 -*-
import numpy as np
import matplotlib.pyplot as plt

class gradient:
    def __init__(self, times):
        self.times = times
        self.x = np.arange(0, np.pi*2, np.pi*2/self.times)        
        self.y = [np.sin(xi) for xi in self.x]
        self.seita = np.array([0.,0.,0.,0.])
        self.step = 0.001
        self.matching()
    def matching(self):
        store_seita = []
        store_seita.append(self.seita)
        k = 1
        while k < 20:
            temp_seita = np.array([0.,0.,0.,0.])
            for j in range(self.times):
                temp_h = 0
                for i in range(len(self.seita)):
                    temp_h += self.seita[i]*np.power(self.x[j], i)
                temp_y = self.y[j]
                temp_x = self.x[j]
                for i in range(len(temp_seita)):
                    temp_seita[i] += (temp_h - temp_y)*np.power(temp_x, i)
            while True:
                print (self.seita)
                temp = self.seita
                cost_first = 0
                for i in range(self.times):
                    temp_h = 0
                    for j in range(len(self.seita)):
                        temp_h += self.seita[j]*np.power(self.x[i], j)
                    temp_y = self.y[i]
                    cost_first += (temp_h - temp_y)*(temp_h - temp_y)/2.0
                self.seita = self.seita - temp_seita*self.step/self.times
                cost_second = 0
                for i in range(self.times):
                    temp_h = 0
                    for j in range(len(self.seita)):
                        temp_h += self.seita[j]*np.power(self.x[i], j)
                    temp_y = self.y[i]
                    cost_second += (temp_h - temp_y)*(temp_h - temp_y)/2.0
                if cost_second - cost_first > 0:
                    self.seita = temp
                    self.step -= 0.0001
                else:
                    break
            store_seita.append(self.seita)
            k += 1
            delta = 0
            for i in range(len(self.seita)):
                delta += (store_seita[0][i]-self.seita[i])*(store_seita[0][i]-self.seita[i])
            delta=np.sqrt(delta)
        while delta > 0.0001:
            temp_seita = np.array([0.,0.,0.,0.])
            for j in range(self.times):
                temp_h = 0
                for i in range(len(self.seita)):
                    temp_h += self.seita[i]*np.power(self.x[j], i)
                temp_y = self.y[j]
                temp_x = self.x[j]
                for i in range(len(temp_seita)):
                    temp_seita[i] += (temp_h - temp_y)*np.power(temp_x, i)
            while True:
                print (self.seita)
                temp = self.seita
                cost_first = 0
                for i in range(self.times):
                    temp_h = 0
                    for j in range(len(self.seita)):
                        temp_h += self.seita[j]*np.power(self.x[i], j)
                    temp_y = self.y[i]
                    cost_first += (temp_h - temp_y)*(temp_h - temp_y)/2.0
                self.seita = self.seita - temp_seita*self.step/self.times
                cost_second = 0
                for i in range(self.times):
                    temp_h = 0
                    for j in range(len(self.seita)):
                        temp_h += self.seita[j]*np.power(self.x[i], j)
                    temp_y = self.y[i]
                    cost_second += (temp_h - temp_y)*(temp_h - temp_y)/2.0
                if cost_second - cost_first > 0:
                    self.seita = temp
                    self.step -= 0.0001
                else:
                    break
            for i in range(1,20):
                store_seita[i-1] = store_seita[i]
            store_seita[19] = self.seita
            delta = 0
            for i in range(len(self.seita)):
                delta += (store_seita[0][i]-self.seita[i])*(store_seita[0][i]-self.seita[i])
            delta=np.sqrt(delta)
        h_label = []
        for i in range(self.times):
            temp=0
            for j in range(len(self.seita)):
                temp += self.seita[j]*np.power(self.x[i], j)
            h_label.append(temp)
        plt.plot(self.x,self.y, 'g')
        plt.axis([0.,2*np.pi,-1.5,1.5])
        plt.plot(self.x, h_label, 'r')
        plt.show()
test = gradient(100)

[ 0.  0.  0.  0.]
[ 0.  0.  0.  0.]
[ 0.  0.  0.  0.]
[ 0.  0.  0.  0.]
[ 0.  0.  0.  0.]
[ 0.  0.  0.  0.]
[ 0.  0.  0.  0.]
[ 0.  0.  0.  0.]
[ 0.  0.  0.  0.]
[  1.36279876e-20  -1.99934198e-04  -1.25622362e-03  -6.69308585e-03]
[  8.47403342e-05   2.28174264e-05  -3.13879434e-04  -1.61762247e-03]
[  1.05186275e-04  -7.50720189e-05  -1.03920106e-03  -5.46852223e-03]
[  1.74379833e-04   7.02066957e-05  -4.99672470e-04  -2.54881352e-03]
[  2.06579325e-04   3.10075922e-05  -9.19590010e-04  -4.76455878e-03]
[ 0.00026682  0.0001317  -0.00061184 -0.00308508]
[ 0.00030577  0.00012625 -0.00085608 -0.00436009]
[ 0.00036085  0.00020127 -0.00068171 -0.00339412]
[ 0.00040368  0.00021521 -0.00082491 -0.00412791]
[ 0.00045578  0.00027545 -0.0007273  -0.00357243]
[ 0.00050083  0.00030054 -0.00081241 -0.00399484]
[ 0.00055121  0.00035225 -0.00075899 -0.00367552]
[ 0.00059753  0.00038374 -0.00081071 -0.00391878]
[ 0.0006469   0.00043053 -0.00078274 -0.00373531]
[ 0.00069394  0.00046567 -0.00081528 -

[ 0.00922756  0.00744038 -0.00249264 -0.00381171]
[ 0.00927388  0.00747744 -0.00250448 -0.00381116]
[ 0.00932019  0.00751449 -0.00251635 -0.00381061]
[ 0.0093665   0.00755153 -0.00252825 -0.00381005]
[ 0.0094128   0.00758855 -0.00254016 -0.00380949]
[ 0.00945909  0.00762556 -0.00255211 -0.00380892]
[ 0.00950537  0.00766255 -0.00256407 -0.00380835]
[ 0.00955164  0.00769953 -0.00257606 -0.00380777]
[ 0.00959791  0.00773649 -0.00258807 -0.00380719]
[ 0.00964416  0.00777344 -0.00260011 -0.0038066 ]
[ 0.00969041  0.00781038 -0.00261217 -0.003806  ]
[ 0.00973665  0.0078473  -0.00262426 -0.00380541]
[ 0.00978288  0.00788421 -0.00263636 -0.0038048 ]
[ 0.00982911  0.00792111 -0.0026485  -0.00380419]
[ 0.00987532  0.00795799 -0.00266065 -0.00380358]
[ 0.00992153  0.00799486 -0.00267283 -0.00380296]
[ 0.00996773  0.00803171 -0.00268503 -0.00380234]
[ 0.01001392  0.00806855 -0.00269725 -0.00380171]
[ 0.01006011  0.00810537 -0.0027095  -0.00380108]
[ 0.01010628  0.00814219 -0.00272177 -0.00380044]


[ 0.0191028   0.01518975 -0.00554811 -0.00359035]
[ 0.01914755  0.01522427 -0.00556411 -0.00358892]
[ 0.0191923   0.01525877 -0.00558013 -0.00358749]
[ 0.01923705  0.01529327 -0.00559616 -0.00358606]
[ 0.01928179  0.01532775 -0.0056122  -0.00358462]
[ 0.01932652  0.01536223 -0.00562826 -0.00358318]
[ 0.01937125  0.0153967  -0.00564434 -0.00358174]
[ 0.01941597  0.01543115 -0.00566043 -0.00358029]
[ 0.01946068  0.0154656  -0.00567654 -0.00357884]
[ 0.01950539  0.01550004 -0.00569265 -0.00357739]
[ 0.01955009  0.01553447 -0.00570879 -0.00357593]
[ 0.01959479  0.01556889 -0.00572494 -0.00357447]
[ 0.01963948  0.0156033  -0.0057411  -0.00357301]
[ 0.01968416  0.0156377  -0.00575728 -0.00357155]
[ 0.01972884  0.01567209 -0.00577347 -0.00357008]
[ 0.01977351  0.01570647 -0.00578968 -0.00356861]
[ 0.01981817  0.01574085 -0.0058059  -0.00356714]
[ 0.01986283  0.01577521 -0.00582213 -0.00356566]
[ 0.01990748  0.01580956 -0.00583838 -0.00356418]
[ 0.01995213  0.01584391 -0.00585465 -0.00356269]


[ 0.02798153  0.02195493 -0.00902257 -0.00324818]
[ 0.02802516  0.02198782 -0.00904097 -0.00324624]
[ 0.02806877  0.0220207  -0.00905937 -0.0032443 ]
[ 0.02811239  0.02205357 -0.00907779 -0.00324235]
[ 0.02815599  0.02208643 -0.00909622 -0.0032404 ]
[ 0.0281996   0.02211929 -0.00911465 -0.00323845]
[ 0.02824319  0.02215214 -0.0091331  -0.0032365 ]
[ 0.02828678  0.02218499 -0.00915155 -0.00323455]
[ 0.02833037  0.02221783 -0.00917001 -0.00323259]
[ 0.02837395  0.02225066 -0.00918848 -0.00323063]
[ 0.02841753  0.02228348 -0.00920696 -0.00322868]
[ 0.0284611   0.0223163  -0.00922545 -0.00322671]
[ 0.02850467  0.02234911 -0.00924395 -0.00322475]
[ 0.02854823  0.02238192 -0.00926246 -0.00322278]
[ 0.02859179  0.02241472 -0.00928098 -0.00322082]
[ 0.02863534  0.02244751 -0.00929951 -0.00321885]
[ 0.02867888  0.02248029 -0.00931804 -0.00321687]
[ 0.02872243  0.02251307 -0.00933659 -0.0032149 ]
[ 0.02876596  0.02254584 -0.00935514 -0.00321293]
[ 0.02880949  0.02257861 -0.0093737  -0.00321095]


[ 0.03541348  0.02751982 -0.01230745 -0.0028879 ]
[ 0.03545629  0.02755169 -0.01232717 -0.00288567]
[ 0.0354991   0.02758354 -0.01234689 -0.00288344]
[ 0.0355419   0.0276154  -0.01236661 -0.00288121]
[ 0.0355847   0.02764724 -0.01238635 -0.00287897]
[ 0.0356275   0.02767909 -0.01240609 -0.00287674]
[ 0.03567028  0.02771092 -0.01242583 -0.0028745 ]
[ 0.03571307  0.02774276 -0.01244558 -0.00287226]
[ 0.03575585  0.02777458 -0.01246534 -0.00287002]
[ 0.03579863  0.0278064  -0.0124851  -0.00286778]
[ 0.0358414   0.02783822 -0.01250487 -0.00286554]
[ 0.03588417  0.02787003 -0.01252465 -0.00286329]
[ 0.03592693  0.02790184 -0.01254443 -0.00286105]
[ 0.03596969  0.02793364 -0.01256422 -0.0028588 ]
[ 0.03601244  0.02796543 -0.01258401 -0.00285655]
[ 0.03605519  0.02799723 -0.01260381 -0.00285431]
[ 0.03609794  0.02802901 -0.01262362 -0.00285205]
[ 0.03614068  0.02806079 -0.01264343 -0.0028498 ]
[ 0.03618342  0.02809257 -0.01266325 -0.00284755]
[ 0.03622615  0.02812434 -0.01268307 -0.0028453 ]


[ 0.04309398  0.03320956 -0.01596232 -0.00246478]
[ 0.04313604  0.0332406  -0.01598293 -0.00246234]
[ 0.04317811  0.03327163 -0.01600354 -0.00245991]
[ 0.04322017  0.03330266 -0.01602415 -0.00245748]
[ 0.04326222  0.03333369 -0.01604477 -0.00245504]
[ 0.04330428  0.03336471 -0.01606539 -0.00245261]
[ 0.04334633  0.03339573 -0.01608601 -0.00245017]
[ 0.04338837  0.03342675 -0.01610664 -0.00244773]
[ 0.04343041  0.03345776 -0.01612727 -0.0024453 ]
[ 0.04347245  0.03348876 -0.01614791 -0.00244286]
[ 0.04351448  0.03351977 -0.01616855 -0.00244042]
[ 0.04355651  0.03355076 -0.01618919 -0.00243798]
[ 0.04359854  0.03358176 -0.01620984 -0.00243554]
[ 0.04364056  0.03361275 -0.01623049 -0.00243309]
[ 0.04368258  0.03364374 -0.01625114 -0.00243065]
[ 0.04372459  0.03367472 -0.0162718  -0.00242821]
[ 0.0437666   0.0337057  -0.01629246 -0.00242576]
[ 0.04380861  0.03373667 -0.01631313 -0.00242332]
[ 0.04385061  0.03376764 -0.0163338  -0.00242087]
[ 0.04389261  0.03379861 -0.01635447 -0.00241842]


[ 0.05143363  0.03934415 -0.02014701 -0.00196339]
[ 0.05147496  0.03937448 -0.0201682  -0.00196082]
[ 0.0515163   0.03940481 -0.02018939 -0.00195825]
[ 0.05155763  0.03943514 -0.02021058 -0.00195568]
[ 0.05159896  0.03946547 -0.02023177 -0.0019531 ]
[ 0.05164028  0.03949579 -0.02025297 -0.00195053]
[ 0.0516816   0.0395261  -0.02027417 -0.00194796]
[ 0.05172292  0.03955642 -0.02029537 -0.00194538]
[ 0.05176423  0.03958673 -0.02031657 -0.00194281]
[ 0.05180555  0.03961704 -0.02033777 -0.00194023]
[ 0.05184685  0.03964735 -0.02035898 -0.00193766]
[ 0.05188816  0.03967765 -0.02038018 -0.00193508]
[ 0.05192946  0.03970795 -0.02040139 -0.00193251]
[ 0.05197075  0.03973824 -0.02042261 -0.00192993]
[ 0.05201205  0.03976854 -0.02044382 -0.00192735]
[ 0.05205334  0.03979883 -0.02046504 -0.00192477]
[ 0.05209462  0.03982911 -0.02048625 -0.00192219]
[ 0.05213591  0.0398594  -0.02050747 -0.00191961]
[ 0.05217719  0.03988968 -0.0205287  -0.00191703]
[ 0.05221846  0.03991996 -0.02054992 -0.00191445]


[ 0.05853497  0.04454839 -0.02383828 -0.00151185]
[ 0.05857574  0.04457823 -0.02385974 -0.00150921]
[ 0.05861649  0.04460807 -0.0238812  -0.00150657]
[ 0.05865725  0.04463791 -0.02390266 -0.00150392]
[ 0.058698    0.04466775 -0.02392413 -0.00150128]
[ 0.05873875  0.04469758 -0.02394559 -0.00149863]
[ 0.0587795   0.04472741 -0.02396705 -0.00149599]
[ 0.05882024  0.04475724 -0.02398852 -0.00149334]
[ 0.05886098  0.04478706 -0.02400999 -0.0014907 ]
[ 0.05890171  0.04481689 -0.02403145 -0.00148805]
[ 0.05894245  0.04484671 -0.02405292 -0.00148541]
[ 0.05898318  0.04487653 -0.02407439 -0.00148276]
[ 0.0590239   0.04490634 -0.02409586 -0.00148011]
[ 0.05906463  0.04493615 -0.02411734 -0.00147746]
[ 0.05910535  0.04496596 -0.02413881 -0.00147482]
[ 0.05914606  0.04499577 -0.02416028 -0.00147217]
[ 0.05918678  0.04502557 -0.02418176 -0.00146952]
[ 0.05922749  0.04505538 -0.02420323 -0.00146687]
[ 0.0592682   0.04508518 -0.02422471 -0.00146422]
[ 0.0593089   0.04511497 -0.02424619 -0.00146157]


[ 0.06602233  0.05002782 -0.02782239 -0.00101827]
[ 0.06606251  0.05005722 -0.02784398 -0.00101559]
[ 0.06610269  0.05008662 -0.02786557 -0.0010129 ]
[ 0.06614287  0.05011602 -0.02788716 -0.00101021]
[ 0.06618305  0.05014542 -0.02790875 -0.00100752]
[ 0.06622322  0.05017481 -0.02793034 -0.00100483]
[ 0.06626339  0.0502042  -0.02795193 -0.00100214]
[ 0.06630356  0.0502336  -0.02797353 -0.00099946]
[ 0.06634372  0.05026298 -0.02799512 -0.00099677]
[ 0.06638388  0.05029237 -0.02801671 -0.00099408]
[ 0.06642404  0.05032175 -0.02803831 -0.00099139]
[ 0.0664642   0.05035113 -0.0280599  -0.0009887 ]
[ 0.06650435  0.05038051 -0.02808149 -0.00098601]
[ 0.0665445   0.05040989 -0.02810309 -0.00098332]
[ 0.06658464  0.05043927 -0.02812468 -0.00098063]
[ 0.06662479  0.05046864 -0.02814628 -0.00097794]
[ 0.06666493  0.05049801 -0.02816787 -0.00097525]
[ 0.06670506  0.05052738 -0.02818947 -0.00097256]
[ 0.0667452   0.05055674 -0.02821106 -0.00096987]
[ 0.06678533  0.05058611 -0.02823266 -0.00096717]


[ 0.07285064  0.05502521 -0.03151715 -0.00055669]
[ 0.07289032  0.05505426 -0.03153876 -0.00055398]
[ 0.07293     0.05508331 -0.03156037 -0.00055127]
[ 0.07296967  0.05511236 -0.03158198 -0.00054857]
[ 0.07300934  0.05514141 -0.03160359 -0.00054586]
[ 0.07304901  0.05517045 -0.0316252  -0.00054315]
[ 0.07308867  0.05519949 -0.03164681 -0.00054044]
[ 0.07312834  0.05522853 -0.03166842 -0.00053773]
[ 0.073168    0.05525757 -0.03169003 -0.00053502]
[ 0.07320765  0.0552866  -0.03171164 -0.00053231]
[ 0.0732473   0.05531564 -0.03173325 -0.00052961]
[ 0.07328695  0.05534467 -0.03175486 -0.0005269 ]
[ 0.0733266   0.0553737  -0.03177647 -0.00052419]
[ 0.07336624  0.05540272 -0.03179808 -0.00052148]
[ 0.07340589  0.05543175 -0.03181968 -0.00051877]
[ 0.07344552  0.05546077 -0.03184129 -0.00051606]
[ 0.07348516  0.0554898  -0.0318629  -0.00051335]
[ 0.07352479  0.05551882 -0.03188451 -0.00051064]
[ 0.07356442  0.05554783 -0.03190612 -0.00050793]
[ 0.07360405  0.05557685 -0.03192773 -0.00050523]


[ 0.07931968  0.05976445 -0.03505836 -0.00011193]
[ 0.07935889  0.0597932  -0.03507993 -0.00010922]
[ 0.0793981   0.05982194 -0.03510149 -0.0001065 ]
[ 0.07943731  0.05985069 -0.03512306 -0.00010379]
[ 0.07947651  0.05987943 -0.03514462 -0.00010107]
[  7.95157130e-02   5.99081712e-02  -3.51661897e-02  -9.83606552e-05]
[  7.95549106e-02   5.99369101e-02  -3.51877541e-02  -9.56465139e-05]
[  7.95941053e-02   5.99656471e-02  -3.52093181e-02  -9.29323681e-05]
[  7.96332972e-02   5.99943824e-02  -3.52308817e-02  -9.02182179e-05]
[  7.96724863e-02   6.00231159e-02  -3.52524448e-02  -8.75040638e-05]
[  7.97116726e-02   6.00518477e-02  -3.52740075e-02  -8.47899060e-05]
[  7.97508562e-02   6.00805777e-02  -3.52955698e-02  -8.20757450e-05]
[  7.97900369e-02   6.01093060e-02  -3.53171317e-02  -7.93615810e-05]
[  7.98292148e-02   6.01380325e-02  -3.53386931e-02  -7.66474143e-05]
[  7.98683899e-02   6.01667572e-02  -3.53602541e-02  -7.39332453e-05]
[  7.99075623e-02   6.01954802e-02  -3.53818146e-0

[ 0.08513155  0.06402884 -0.03826641  0.00029237]
[ 0.08517034  0.06405733 -0.0382879   0.00029509]
[ 0.08520914  0.06408582 -0.03830939  0.0002978 ]
[ 0.08524793  0.06411431 -0.03833088  0.00030051]
[ 0.08528673  0.0641428  -0.03835237  0.00030322]
[ 0.08532551  0.06417129 -0.03837385  0.00030593]
[ 0.0853643   0.06419978 -0.03839534  0.00030864]
[ 0.08540308  0.06422826 -0.03841683  0.00031136]
[ 0.08544186  0.06425674 -0.03843831  0.00031407]
[ 0.08548064  0.06428522 -0.03845979  0.00031678]
[ 0.08551941  0.0643137  -0.03848128  0.00031949]
[ 0.08555818  0.06434218 -0.03850276  0.0003222 ]
[ 0.08559695  0.06437065 -0.03852424  0.00032491]
[ 0.08563572  0.06439913 -0.03854572  0.00032762]
[ 0.08567448  0.0644276  -0.03856721  0.00033034]
[ 0.08571324  0.06445607 -0.03858869  0.00033305]
[ 0.085752    0.06448454 -0.03861017  0.00033576]
[ 0.08579076  0.06451301 -0.03863165  0.00033847]
[ 0.08582951  0.06454147 -0.03865312  0.00034118]
[ 0.08586826  0.06456994 -0.0386746   0.00034389]


[ 0.0923015   0.06930099 -0.04225172  0.00079591]
[ 0.0923398   0.06932919 -0.04227308  0.00079861]
[ 0.0923781   0.06935738 -0.04229444  0.00080131]
[ 0.09241639  0.06938558 -0.04231579  0.00080401]
[ 0.09245468  0.06941377 -0.04233715  0.00080672]
[ 0.09249296  0.06944196 -0.0423585   0.00080942]
[ 0.09253124  0.06947015 -0.04237986  0.00081212]
[ 0.09256953  0.06949834 -0.04240121  0.00081482]
[ 0.0926078   0.06952653 -0.04242256  0.00081752]
[ 0.09264608  0.06955471 -0.04244391  0.00082022]
[ 0.09268435  0.0695829  -0.04246526  0.00082292]
[ 0.09272262  0.06961108 -0.04248661  0.00082562]
[ 0.09276089  0.06963926 -0.04250796  0.00082832]
[ 0.09279915  0.06966744 -0.04252931  0.00083102]
[ 0.09283742  0.06969562 -0.04255066  0.00083372]
[ 0.09287568  0.0697238  -0.042572    0.00083642]
[ 0.09291393  0.06975197 -0.04259335  0.00083912]
[ 0.09295219  0.06978014 -0.04261469  0.00084182]
[ 0.09299044  0.06980832 -0.04263604  0.00084452]
[ 0.09302869  0.06983649 -0.04265738  0.00084722]


[ 0.09900096  0.07424052 -0.04599791  0.00127011]
[ 0.09903879  0.07426845 -0.04601911  0.00127279]
[ 0.09907662  0.07429639 -0.04604032  0.00127548]
[ 0.09911445  0.07432432 -0.04606153  0.00127817]
[ 0.09915227  0.07435225 -0.04608273  0.00128085]
[ 0.09919009  0.07438017 -0.04610394  0.00128354]
[ 0.09922791  0.0744081  -0.04612514  0.00128623]
[ 0.09926573  0.07443603 -0.04614635  0.00128891]
[ 0.09930354  0.07446395 -0.04616755  0.0012916 ]
[ 0.09934135  0.07449187 -0.04618875  0.00129428]
[ 0.09937916  0.07451979 -0.04620995  0.00129697]
[ 0.09941697  0.07454771 -0.04623115  0.00129965]
[ 0.09945477  0.07457563 -0.04625235  0.00130234]
[ 0.09949257  0.07460355 -0.04627355  0.00130502]
[ 0.09953037  0.07463146 -0.04629474  0.00130771]
[ 0.09956817  0.07465937 -0.04631594  0.00131039]
[ 0.09960596  0.07468729 -0.04633714  0.00131308]
[ 0.09964375  0.0747152  -0.04635833  0.00131576]
[ 0.09968154  0.07474311 -0.04637952  0.00131845]
[ 0.09971932  0.07477101 -0.04640072  0.00132113]


[ 0.10517072  0.07880235 -0.04946381  0.00170933]
[ 0.10520812  0.07883004 -0.04948486  0.00171199]
[ 0.10524553  0.07885774 -0.04950592  0.00171466]
[ 0.10528293  0.07888544 -0.04952697  0.00171733]
[ 0.10532033  0.07891313 -0.04954802  0.00172   ]
[ 0.10535773  0.07894082 -0.04956908  0.00172267]
[ 0.10539512  0.07896851 -0.04959013  0.00172534]
[ 0.10543251  0.0789962  -0.04961118  0.00172801]
[ 0.1054699   0.07902389 -0.04963223  0.00173068]
[ 0.10550729  0.07905158 -0.04965327  0.00173335]
[ 0.10554467  0.07907926 -0.04967432  0.00173601]
[ 0.10558206  0.07910695 -0.04969537  0.00173868]
[ 0.10561943  0.07913463 -0.04971641  0.00174135]
[ 0.10565681  0.07916231 -0.04973746  0.00174402]
[ 0.10569419  0.07918999 -0.0497585   0.00174669]
[ 0.10573156  0.07921767 -0.04977954  0.00174935]
[ 0.10576893  0.07924535 -0.04980058  0.00175202]
[ 0.10580629  0.07927302 -0.04982162  0.00175469]
[ 0.10584365  0.0793007  -0.04984266  0.00175736]
[ 0.10588102  0.07932837 -0.0498637   0.00176002]


[ 0.11171501  0.08365572 -0.05315448  0.00217736]
[ 0.11175197  0.08368317 -0.05317536  0.00218001]
[ 0.11178892  0.08371062 -0.05319624  0.00218266]
[ 0.11182588  0.08373808 -0.05321712  0.00218531]
[ 0.11186283  0.08376552 -0.053238    0.00218796]
[ 0.11189978  0.08379297 -0.05325888  0.00219061]
[ 0.11193672  0.08382042 -0.05327975  0.00219326]
[ 0.11197366  0.08384787 -0.05330063  0.0021959 ]
[ 0.11201061  0.08387531 -0.0533215   0.00219855]
[ 0.11204754  0.08390275 -0.05334238  0.0022012 ]
[ 0.11208448  0.08393019 -0.05336325  0.00220385]
[ 0.11212141  0.08395763 -0.05338412  0.00220649]
[ 0.11215834  0.08398507 -0.05340499  0.00220914]
[ 0.11219527  0.08401251 -0.05342586  0.00221179]
[ 0.1122322   0.08403995 -0.05344673  0.00221444]
[ 0.11226912  0.08406738 -0.0534676   0.00221708]
[ 0.11230604  0.08409481 -0.05348846  0.00221973]
[ 0.11234296  0.08412225 -0.05350933  0.00222238]
[ 0.11237987  0.08414968 -0.05353019  0.00222502]
[ 0.11241678  0.0841771  -0.05355105  0.00222767]


[ 0.11898366  0.08906512 -0.05726903  0.0026994 ]
[ 0.11902012  0.08909231 -0.05728971  0.00270203]
[ 0.11905658  0.0891195  -0.05731038  0.00270465]
[ 0.11909303  0.08914668 -0.05733106  0.00270728]
[ 0.11912949  0.08917386 -0.05735173  0.0027099 ]
[ 0.11916594  0.08920104 -0.05737241  0.00271252]
[ 0.11920239  0.08922822 -0.05739308  0.00271515]
[ 0.11923883  0.0892554  -0.05741375  0.00271777]
[ 0.11927528  0.08928258 -0.05743442  0.00272039]
[ 0.11931172  0.08930976 -0.05745509  0.00272301]
[ 0.11934816  0.08933693 -0.05747576  0.00272564]
[ 0.11938459  0.0893641  -0.05749642  0.00272826]
[ 0.11942103  0.08939128 -0.05751709  0.00273088]
[ 0.11945746  0.08941845 -0.05753776  0.00273351]
[ 0.11949389  0.08944562 -0.05755842  0.00273613]
[ 0.11953031  0.08947278 -0.05757908  0.00273875]
[ 0.11956674  0.08949995 -0.05759975  0.00274137]
[ 0.11960316  0.08952712 -0.05762041  0.00274399]
[ 0.11963958  0.08955428 -0.05764107  0.00274661]
[ 0.11967599  0.08958144 -0.05766172  0.00274924]


[ 0.12529056  0.09377573 -0.06085113  0.003154  ]
[ 0.12532659  0.09380269 -0.06087162  0.0031566 ]
[ 0.12536262  0.09382964 -0.06089212  0.0031592 ]
[ 0.12539865  0.0938566  -0.06091261  0.0031618 ]
[ 0.12543467  0.09388355 -0.0609331   0.0031644 ]
[ 0.12547069  0.0939105  -0.06095359  0.003167  ]
[ 0.12550671  0.09393745 -0.06097408  0.0031696 ]
[ 0.12554272  0.0939644  -0.06099457  0.0031722 ]
[ 0.12557874  0.09399135 -0.06101506  0.0031748 ]
[ 0.12561475  0.0940183  -0.06103554  0.0031774 ]
[ 0.12565076  0.09404525 -0.06105603  0.00318   ]
[ 0.12568676  0.09407219 -0.06107651  0.0031826 ]
[ 0.12572277  0.09409913 -0.06109699  0.0031852 ]
[ 0.12575877  0.09412608 -0.06111748  0.0031878 ]
[ 0.12579476  0.09415302 -0.06113796  0.0031904 ]
[ 0.12583076  0.09417996 -0.06115844  0.003193  ]
[ 0.12586675  0.09420689 -0.06117891  0.0031956 ]
[ 0.12590275  0.09423383 -0.06119939  0.0031982 ]
[ 0.12593873  0.09426077 -0.06121987  0.0032008 ]
[ 0.12597472  0.0942877  -0.06124034  0.00320339]


[ 0.13180777  0.09866069 -0.06456363  0.00362518]
[ 0.13184336  0.09868741 -0.06458393  0.00362775]
[ 0.13187894  0.09871413 -0.06460423  0.00363033]
[ 0.13191452  0.09874085 -0.06462453  0.0036329 ]
[ 0.1319501   0.09876757 -0.06464483  0.00363548]
[ 0.13198568  0.09879429 -0.06466513  0.00363806]
[ 0.13202125  0.098821   -0.06468542  0.00364063]
[ 0.13205682  0.09884772 -0.06470572  0.00364321]
[ 0.13209239  0.09887443 -0.06472601  0.00364578]
[ 0.13212796  0.09890114 -0.0647463   0.00364836]
[ 0.13216352  0.09892786 -0.06476659  0.00365093]
[ 0.13219908  0.09895457 -0.06478688  0.00365351]
[ 0.13223464  0.09898127 -0.06480717  0.00365609]
[ 0.1322702   0.09900798 -0.06482746  0.00365866]
[ 0.13230575  0.09903469 -0.06484775  0.00366123]
[ 0.13234131  0.09906139 -0.06486803  0.00366381]
[ 0.13237686  0.0990881  -0.06488832  0.00366638]
[ 0.1324124   0.0991148  -0.0649086   0.00366896]
[ 0.13244795  0.0991415  -0.06492889  0.00367153]
[ 0.13248349  0.0991682  -0.06494917  0.00367411]


[ 0.13842026  0.10363569 -0.06834135  0.00410462]
[ 0.1384554   0.10366218 -0.06836145  0.00410717]
[ 0.13849053  0.10368866 -0.06838155  0.00410972]
[ 0.13852566  0.10371514 -0.06840165  0.00411227]
[ 0.13856079  0.10374162 -0.06842175  0.00411482]
[ 0.13859591  0.1037681  -0.06844184  0.00411737]
[ 0.13863104  0.10379458 -0.06846194  0.00411992]
[ 0.13866616  0.10382106 -0.06848204  0.00412247]
[ 0.13870127  0.10384754 -0.06850213  0.00412502]
[ 0.13873639  0.10387401 -0.06852222  0.00412757]
[ 0.1387715   0.10390049 -0.06854231  0.00413012]
[ 0.13880661  0.10392696 -0.0685624   0.00413267]
[ 0.13884172  0.10395343 -0.06858249  0.00413522]
[ 0.13887683  0.1039799  -0.06860258  0.00413777]
[ 0.13891193  0.10400637 -0.06862267  0.00414032]
[ 0.13894703  0.10403284 -0.06864276  0.00414287]
[ 0.13898213  0.1040593  -0.06866284  0.00414542]
[ 0.13901723  0.10408577 -0.06868293  0.00414797]
[ 0.13905232  0.10411223 -0.06870301  0.00415051]
[ 0.13908741  0.1041387  -0.06872309  0.00415306]


[ 0.14439356  0.10814647 -0.07176317  0.00453885]
[ 0.14442829  0.10817274 -0.07178309  0.00454137]
[ 0.14446302  0.10819901 -0.071803    0.0045439 ]
[ 0.14449774  0.10822528 -0.07182292  0.00454643]
[ 0.14453246  0.10825155 -0.07184284  0.00454896]
[ 0.14456717  0.10827781 -0.07186275  0.00455148]
[ 0.14460189  0.10830408 -0.07188266  0.00455401]
[ 0.1446366   0.10833034 -0.07190258  0.00455654]
[ 0.14467131  0.1083566  -0.07192249  0.00455906]
[ 0.14470602  0.10838287 -0.0719424   0.00456159]
[ 0.14474073  0.10840913 -0.07196231  0.00456412]
[ 0.14477543  0.10843539 -0.07198222  0.00456664]
[ 0.14481013  0.10846164 -0.07200212  0.00456917]
[ 0.14484483  0.1084879  -0.07202203  0.00457169]
[ 0.14487953  0.10851416 -0.07204193  0.00457422]
[ 0.14491422  0.10854041 -0.07206184  0.00457674]
[ 0.14494891  0.10856666 -0.07208174  0.00457927]
[ 0.1449836   0.10859291 -0.07210164  0.0045818 ]
[ 0.14501829  0.10861916 -0.07212154  0.00458432]
[ 0.14505297  0.10864541 -0.07214144  0.00458685]


[ 0.15053776  0.11280332 -0.07529199  0.00498659]
[ 0.15057206  0.11282937 -0.07531172  0.00498909]
[ 0.15060637  0.11285542 -0.07533144  0.00499159]
[ 0.15064067  0.11288147 -0.07535117  0.0049941 ]
[ 0.15067497  0.11290752 -0.0753709   0.0049966 ]
[ 0.15070927  0.11293357 -0.07539062  0.0049991 ]
[ 0.15074357  0.11295961 -0.07541035  0.0050016 ]
[ 0.15077786  0.11298566 -0.07543007  0.00500411]
[ 0.15081215  0.1130117  -0.07544979  0.00500661]
[ 0.15084644  0.11303774 -0.07546952  0.00500911]
[ 0.15088073  0.11306378 -0.07548924  0.00501161]
[ 0.15091501  0.11308982 -0.07550896  0.00501411]
[ 0.15094929  0.11311586 -0.07552867  0.00501662]
[ 0.15098357  0.1131419  -0.07554839  0.00501912]
[ 0.15101785  0.11316794 -0.07556811  0.00502162]
[ 0.15105212  0.11319397 -0.07558782  0.00502412]
[ 0.15108639  0.11322    -0.07560754  0.00502662]
[ 0.15112066  0.11324604 -0.07562725  0.00502912]
[ 0.15115493  0.11327207 -0.07564696  0.00503162]
[ 0.1511892   0.1132981  -0.07566667  0.00503412]


[ 0.15856964  0.11891777 -0.07991892  0.00557353]
[ 0.1586034   0.11894353 -0.0799384   0.005576  ]
[ 0.15863715  0.11896929 -0.07995788  0.00557847]
[ 0.15867091  0.11899506 -0.07997736  0.00558094]
[ 0.15870466  0.11902082 -0.07999684  0.00558341]
[ 0.15873841  0.11904658 -0.08001632  0.00558588]
[ 0.15877215  0.11907234 -0.08003579  0.00558835]
[ 0.1588059   0.1190981  -0.08005527  0.00559082]
[ 0.15883964  0.11912385 -0.08007474  0.00559329]
[ 0.15887338  0.11914961 -0.08009421  0.00559576]
[ 0.15890712  0.11917536 -0.08011368  0.00559823]
[ 0.15894085  0.11920111 -0.08013315  0.0056007 ]
[ 0.15897459  0.11922687 -0.08015262  0.00560317]
[ 0.15900832  0.11925262 -0.08017209  0.00560564]
[ 0.15904205  0.11927837 -0.08019156  0.00560811]
[ 0.15907577  0.11930411 -0.08021102  0.00561058]
[ 0.1591095   0.11932986 -0.08023049  0.00561305]
[ 0.15914322  0.11935561 -0.08024995  0.00561552]
[ 0.15917694  0.11938135 -0.08026942  0.00561799]
[ 0.15921065  0.11940709 -0.08028888  0.00562046]


[ 0.16550863  0.12422552 -0.08392914  0.00608211]
[ 0.16554191  0.12425104 -0.08394841  0.00608455]
[ 0.16557519  0.12427655 -0.08396767  0.00608699]
[ 0.16560847  0.12430207 -0.08398693  0.00608943]
[ 0.16564175  0.12432758 -0.08400619  0.00609188]
[ 0.16567502  0.12435309 -0.08402545  0.00609432]
[ 0.16570829  0.1243786  -0.08404471  0.00609676]
[ 0.16574156  0.12440411 -0.08406397  0.0060992 ]
[ 0.16577483  0.12442962 -0.08408323  0.00610164]
[ 0.1658081   0.12445513 -0.08410249  0.00610409]
[ 0.16584136  0.12448064 -0.08412174  0.00610653]
[ 0.16587462  0.12450614 -0.084141    0.00610897]
[ 0.16590788  0.12453164 -0.08416025  0.00611141]
[ 0.16594114  0.12455715 -0.0841795   0.00611385]
[ 0.16597439  0.12458265 -0.08419875  0.00611629]
[ 0.16600764  0.12460815 -0.084218    0.00611873]
[ 0.16604089  0.12463365 -0.08423725  0.00612117]
[ 0.16607414  0.12465915 -0.0842565   0.00612362]
[ 0.16610738  0.12468464 -0.08427575  0.00612606]
[ 0.16614063  0.12471014 -0.08429499  0.0061285 ]


[ 0.17202169  0.1292295  -0.08770426  0.00656074]
[ 0.17205453  0.12925478 -0.08772332  0.00656315]
[ 0.17208736  0.12928006 -0.08774238  0.00656557]
[ 0.1721202   0.12930535 -0.08776143  0.00656798]
[ 0.17215303  0.12933063 -0.08778049  0.0065704 ]
[ 0.17218586  0.12935591 -0.08779955  0.00657282]
[ 0.17221868  0.12938118 -0.0878186   0.00657523]
[ 0.17225151  0.12940646 -0.08783766  0.00657765]
[ 0.17228433  0.12943174 -0.08785671  0.00658006]
[ 0.17231715  0.12945701 -0.08787577  0.00658248]
[ 0.17234996  0.12948228 -0.08789482  0.00658489]
[ 0.17238278  0.12950756 -0.08791387  0.00658731]
[ 0.17241559  0.12953283 -0.08793292  0.00658972]
[ 0.1724484   0.1295581  -0.08795196  0.00659214]
[ 0.17248121  0.12958337 -0.08797101  0.00659455]
[ 0.17251402  0.12960863 -0.08799006  0.00659697]
[ 0.17254682  0.1296339  -0.0880091   0.00659938]
[ 0.17257962  0.12965917 -0.08802815  0.0066018 ]
[ 0.17261242  0.12968443 -0.08804719  0.00660421]
[ 0.17264522  0.12970969 -0.08806623  0.00660662]


[ 0.17877126  0.13443836 -0.09162797  0.00705807]
[ 0.17880363  0.1344634  -0.09164682  0.00706046]
[ 0.178836    0.13448844 -0.09166567  0.00706284]
[ 0.17886837  0.13451348 -0.09168452  0.00706523]
[ 0.17890074  0.13453852 -0.09170336  0.00706762]
[ 0.17893311  0.13456356 -0.09172221  0.00707001]
[ 0.17896547  0.13458859 -0.09174105  0.0070724 ]
[ 0.17899783  0.13461363 -0.0917599   0.00707478]
[ 0.17903019  0.13463866 -0.09177874  0.00707717]
[ 0.17906255  0.1346637  -0.09179758  0.00707956]
[ 0.1790949   0.13468873 -0.09181642  0.00708195]
[ 0.17912725  0.13471376 -0.09183526  0.00708434]
[ 0.1791596   0.13473879 -0.09185409  0.00708672]
[ 0.17919195  0.13476382 -0.09187293  0.00708911]
[ 0.1792243   0.13478885 -0.09189177  0.0070915 ]
[ 0.17925664  0.13481387 -0.0919106   0.00709388]
[ 0.17928898  0.1348389  -0.09192943  0.00709627]
[ 0.17932132  0.13486392 -0.09194827  0.00709866]
[ 0.17935366  0.13488894 -0.0919671   0.00710104]
[ 0.17938599  0.13491397 -0.09198593  0.00710343]


[ 0.18478679  0.13910119 -0.09513509  0.00750247]
[ 0.18481875  0.13912602 -0.09515375  0.00750483]
[ 0.18485071  0.13915085 -0.09517241  0.00750719]
[ 0.18488266  0.13917567 -0.09519106  0.00750956]
[ 0.18491462  0.13920049 -0.09520972  0.00751192]
[ 0.18494657  0.13922532 -0.09522838  0.00751428]
[ 0.18497852  0.13925014 -0.09524703  0.00751665]
[ 0.18501047  0.13927496 -0.09526569  0.00751901]
[ 0.18504241  0.13929978 -0.09528434  0.00752137]
[ 0.18507436  0.13932459 -0.09530299  0.00752374]
[ 0.1851063   0.13934941 -0.09532164  0.0075261 ]
[ 0.18513824  0.13937422 -0.09534029  0.00752846]
[ 0.18517018  0.13939904 -0.09535894  0.00753083]
[ 0.18520211  0.13942385 -0.09537759  0.00753319]
[ 0.18523404  0.13944866 -0.09539623  0.00753555]
[ 0.18526597  0.13947347 -0.09541488  0.00753791]
[ 0.1852979   0.13949828 -0.09543352  0.00754028]
[ 0.18532983  0.13952309 -0.09545217  0.00754264]
[ 0.18536175  0.1395479  -0.09547081  0.007545  ]
[ 0.18539368  0.13957271 -0.09548945  0.00754736]


[ 0.19003078  0.14318214 -0.09820035  0.00789077]
[ 0.19006238  0.14320678 -0.09821884  0.00789312]
[ 0.19009398  0.14323142 -0.09823734  0.00789546]
[ 0.19012558  0.14325605 -0.09825583  0.0078978 ]
[ 0.19015717  0.14328069 -0.09827432  0.00790014]
[ 0.19018876  0.14330532 -0.09829281  0.00790248]
[ 0.19022035  0.14332996 -0.0983113   0.00790483]
[ 0.19025194  0.14335459 -0.09832979  0.00790717]
[ 0.19028353  0.14337922 -0.09834828  0.00790951]
[ 0.19031511  0.14340385 -0.09836676  0.00791185]
[ 0.19034669  0.14342848 -0.09838525  0.00791419]
[ 0.19037827  0.1434531  -0.09840373  0.00791653]
[ 0.19040985  0.14347773 -0.09842222  0.00791888]
[ 0.19044142  0.14350235 -0.0984407   0.00792122]
[ 0.19047299  0.14352698 -0.09845918  0.00792356]
[ 0.19050456  0.1435516  -0.09847766  0.0079259 ]
[ 0.19053613  0.14357622 -0.09849614  0.00792824]
[ 0.1905677   0.14360084 -0.09851462  0.00793058]
[ 0.19059926  0.14362546 -0.09853309  0.00793292]
[ 0.19063082  0.14365008 -0.09855157  0.00793526]


[ 0.19515308  0.14718327 -0.10120179  0.0082709 ]
[ 0.19518433  0.14720773 -0.10122013  0.00827322]
[ 0.19521558  0.14723218 -0.10123846  0.00827554]
[ 0.19524682  0.14725663 -0.10125679  0.00827787]
[ 0.19527806  0.14728108 -0.10127512  0.00828019]
[ 0.1953093   0.14730553 -0.10129345  0.00828251]
[ 0.19534054  0.14732998 -0.10131177  0.00828483]
[ 0.19537178  0.14735443 -0.1013301   0.00828715]
[ 0.19540301  0.14737887 -0.10134843  0.00828947]
[ 0.19543424  0.14740332 -0.10136675  0.00829179]
[ 0.19546547  0.14742776 -0.10138507  0.00829411]
[ 0.19549669  0.14745221 -0.1014034   0.00829643]
[ 0.19552792  0.14747665 -0.10142172  0.00829875]
[ 0.19555914  0.14750109 -0.10144004  0.00830107]
[ 0.19559036  0.14752553 -0.10145836  0.00830339]
[ 0.19562158  0.14754997 -0.10147668  0.00830571]
[ 0.19565279  0.14757441 -0.10149499  0.00830803]
[ 0.19568401  0.14759884 -0.10151331  0.00831035]
[ 0.19571522  0.14762328 -0.10153163  0.00831267]
[ 0.19574643  0.14764771 -0.10154994  0.00831499]


[ 0.2012059   0.15193068 -0.10475802  0.00872117]
[ 0.20123673  0.15195492 -0.10477616  0.00872347]
[ 0.20126756  0.15197915 -0.1047943   0.00872576]
[ 0.20129839  0.15200339 -0.10481244  0.00872806]
[ 0.20132921  0.15202762 -0.10483057  0.00873035]
[ 0.20136003  0.15205185 -0.10484871  0.00873265]
[ 0.20139085  0.15207608 -0.10486685  0.00873495]
[ 0.20142167  0.15210031 -0.10488498  0.00873724]
[ 0.20145249  0.15212454 -0.10490312  0.00873954]
[ 0.2014833   0.15214877 -0.10492125  0.00874183]
[ 0.20151411  0.152173   -0.10493938  0.00874413]
[ 0.20154492  0.15219722 -0.10495751  0.00874642]
[ 0.20157573  0.15222145 -0.10497564  0.00874872]
[ 0.20160653  0.15224567 -0.10499377  0.00875101]
[ 0.20163734  0.15226989 -0.1050119   0.00875331]
[ 0.20166814  0.15229411 -0.10503003  0.0087556 ]
[ 0.20169894  0.15231833 -0.10504815  0.0087579 ]
[ 0.20172973  0.15234255 -0.10506628  0.00876019]
[ 0.20176053  0.15236677 -0.1050844   0.00876249]
[ 0.20179132  0.15239098 -0.10510253  0.00876478]


[ 0.20714741  0.15661182 -0.10825915  0.00916433]
[ 0.20717784  0.15663584 -0.1082771   0.0091666 ]
[ 0.20720825  0.15665986 -0.10829505  0.00916887]
[ 0.20723867  0.15668388 -0.108313    0.00917114]
[ 0.20726908  0.1567079  -0.10833095  0.00917341]
[ 0.2072995   0.15673192 -0.1083489   0.00917568]
[ 0.20732991  0.15675594 -0.10836685  0.00917796]
[ 0.20736031  0.15677995 -0.1083848   0.00918023]
[ 0.20739072  0.15680397 -0.10840274  0.0091825 ]
[ 0.20742112  0.15682798 -0.10842069  0.00918477]
[ 0.20745153  0.15685199 -0.10843863  0.00918704]
[ 0.20748193  0.156876   -0.10845658  0.00918931]
[ 0.20751232  0.15690001 -0.10847452  0.00919158]
[ 0.20754272  0.15692402 -0.10849246  0.00919385]
[ 0.20757311  0.15694803 -0.1085104   0.00919612]
[ 0.2076035   0.15697204 -0.10852834  0.00919839]
[ 0.20763389  0.15699604 -0.10854628  0.00920066]
[ 0.20766428  0.15702005 -0.10856421  0.00920293]
[ 0.20769466  0.15704405 -0.10858215  0.0092052 ]
[ 0.20772505  0.15706805 -0.10860008  0.00920747]


[ 0.21264948  0.16096581 -0.11151068  0.00957577]
[ 0.21267952  0.16098964 -0.11152846  0.00957802]
[ 0.21270956  0.16101346 -0.11154623  0.00958026]
[ 0.2127396   0.16103728 -0.11156401  0.00958251]
[ 0.21276963  0.1610611  -0.11158179  0.00958476]
[ 0.21279966  0.16108492 -0.11159956  0.00958701]
[ 0.21282969  0.16110874 -0.11161733  0.00958926]
[ 0.21285972  0.16113255 -0.1116351   0.00959151]
[ 0.21288975  0.16115637 -0.11165288  0.00959376]
[ 0.21291977  0.16118018 -0.11167065  0.00959601]
[ 0.21294979  0.161204   -0.11168842  0.00959825]
[ 0.21297981  0.16122781 -0.11170618  0.0096005 ]
[ 0.21300983  0.16125162 -0.11172395  0.00960275]
[ 0.21303985  0.16127543 -0.11174172  0.009605  ]
[ 0.21306986  0.16129924 -0.11175948  0.00960724]
[ 0.21309987  0.16132305 -0.11177725  0.00960949]
[ 0.21312988  0.16134686 -0.11179501  0.00961174]
[ 0.21315989  0.16137066 -0.11181277  0.00961399]
[ 0.21318989  0.16139447 -0.11183053  0.00961623]
[ 0.21321989  0.16141827 -0.1118483   0.00961848]


[ 0.21796403  0.16518931 -0.11466015  0.00997418]
[ 0.21799371  0.16521294 -0.11467776  0.00997641]
[ 0.21802338  0.16523657 -0.11469536  0.00997863]
[ 0.21805305  0.1652602  -0.11471297  0.00998086]
[ 0.21808271  0.16528382 -0.11473058  0.00998309]
[ 0.21811238  0.16530745 -0.11474818  0.00998531]
[ 0.21814204  0.16533108 -0.11476579  0.00998754]
[ 0.2181717   0.1653547  -0.11478339  0.00998977]
[ 0.21820136  0.16537832 -0.11480099  0.00999199]
[ 0.21823101  0.16540195 -0.11481859  0.00999422]
[ 0.21826067  0.16542557 -0.11483619  0.00999644]
[ 0.21829032  0.16544919 -0.11485379  0.00999867]
[ 0.21831997  0.16547281 -0.11487139  0.0100009 ]
[ 0.21834962  0.16549642 -0.11488899  0.01000312]
[ 0.21837926  0.16552004 -0.11490659  0.01000535]
[ 0.2184089   0.16554366 -0.11492418  0.01000757]
[ 0.21843855  0.16556727 -0.11494178  0.0100098 ]
[ 0.21846819  0.16559089 -0.11495937  0.01001202]
[ 0.21849782  0.1656145  -0.11497696  0.01001425]
[ 0.21852746  0.16563811 -0.11499455  0.01001647]


[ 0.22327207  0.16942562 -0.11781456  0.0103731 ]
[ 0.22330138  0.16944906 -0.117832    0.01037531]
[ 0.22333068  0.1694725  -0.11784944  0.01037751]
[ 0.22335998  0.16949593 -0.11786688  0.01037972]
[ 0.22338928  0.16951937 -0.11788432  0.01038192]
[ 0.22341857  0.1695428  -0.11790175  0.01038412]
[ 0.22344787  0.16956623 -0.11791919  0.01038633]
[ 0.22347716  0.16958967 -0.11793662  0.01038853]
[ 0.22350645  0.1696131  -0.11795405  0.01039074]
[ 0.22353574  0.16963653 -0.11797149  0.01039294]
[ 0.22356502  0.16965996 -0.11798892  0.01039515]
[ 0.22359431  0.16968338 -0.11800635  0.01039735]
[ 0.22362359  0.16970681 -0.11802378  0.01039955]
[ 0.22365287  0.16973024 -0.11804121  0.01040176]
[ 0.22368215  0.16975366 -0.11805863  0.01040396]
[ 0.22371142  0.16977709 -0.11807606  0.01040617]
[ 0.2237407   0.16980051 -0.11809349  0.01040837]
[ 0.22376997  0.16982393 -0.11811091  0.01041057]
[ 0.22379924  0.16984735 -0.11812833  0.01041277]
[ 0.22382851  0.16987077 -0.11814576  0.01041498]


[ 0.22897705  0.17399932 -0.12121494  0.010803  ]
[ 0.22900596  0.17402255 -0.1212322   0.01080518]
[ 0.22903486  0.17404578 -0.12124946  0.01080736]
[ 0.22906377  0.17406901 -0.12126671  0.01080954]
[ 0.22909267  0.17409224 -0.12128397  0.01081172]
[ 0.22912157  0.17411547 -0.12130122  0.0108139 ]
[ 0.22915047  0.17413869 -0.12131848  0.01081608]
[ 0.22917936  0.17416192 -0.12133573  0.01081826]
[ 0.22920826  0.17418514 -0.12135298  0.01082044]
[ 0.22923715  0.17420837 -0.12137023  0.01082263]
[ 0.22926604  0.17423159 -0.12138748  0.01082481]
[ 0.22929493  0.17425481 -0.12140473  0.01082699]
[ 0.22932382  0.17427803 -0.12142197  0.01082917]
[ 0.2293527   0.17430125 -0.12143922  0.01083135]
[ 0.22938158  0.17432446 -0.12145647  0.01083353]
[ 0.22941046  0.17434768 -0.12147371  0.01083571]
[ 0.22943934  0.1743709  -0.12149095  0.01083789]
[ 0.22946822  0.17439411 -0.1215082   0.01084006]
[ 0.22949709  0.17441732 -0.12152544  0.01084224]
[ 0.22952596  0.17444054 -0.12154268  0.01084442]


[ 0.23545951  0.17922299 -0.12509177  0.01129296]
[ 0.23548797  0.17924598 -0.12510882  0.01129511]
[ 0.23551643  0.17926898 -0.12512587  0.01129727]
[ 0.23554488  0.17929197 -0.12514292  0.01129942]
[ 0.23557333  0.17931496 -0.12515997  0.01130158]
[ 0.23560178  0.17933795 -0.12517701  0.01130373]
[ 0.23563023  0.17936095 -0.12519406  0.01130588]
[ 0.23565868  0.17938393 -0.1252111   0.01130804]
[ 0.23568712  0.17940692 -0.12522815  0.01131019]
[ 0.23571556  0.17942991 -0.12524519  0.01131234]
[ 0.235744    0.1794529  -0.12526223  0.0113145 ]
[ 0.23577244  0.17947588 -0.12527927  0.01131665]
[ 0.23580087  0.17949886 -0.12529631  0.0113188 ]
[ 0.23582931  0.17952185 -0.12531335  0.01132096]
[ 0.23585774  0.17954483 -0.12533039  0.01132311]
[ 0.23588617  0.17956781 -0.12534743  0.01132526]
[ 0.2359146   0.17959079 -0.12536446  0.01132741]
[ 0.23594302  0.17961377 -0.1253815   0.01132957]
[ 0.23597145  0.17963675 -0.12539853  0.01133172]
[ 0.23599987  0.17965972 -0.12541557  0.01133387]


[ 0.24156057  0.184166   -0.12875355  0.01175557]
[ 0.2415886   0.18418878 -0.1287704   0.0117577 ]
[ 0.24161663  0.18421155 -0.12878726  0.01175983]
[ 0.24164466  0.18423432 -0.12880411  0.01176196]
[ 0.24167269  0.18425709 -0.12882096  0.01176409]
[ 0.24170072  0.18427986 -0.12883781  0.01176622]
[ 0.24172874  0.18430263 -0.12885466  0.01176834]
[ 0.24175676  0.18432539 -0.12887151  0.01177047]
[ 0.24178478  0.18434816 -0.12888836  0.0117726 ]
[ 0.24181279  0.18437092 -0.12890521  0.01177473]
[ 0.24184081  0.18439369 -0.12892206  0.01177686]
[ 0.24186882  0.18441645 -0.1289389   0.01177898]
[ 0.24189683  0.18443921 -0.12895575  0.01178111]
[ 0.24192484  0.18446197 -0.12897259  0.01178324]
[ 0.24195285  0.18448473 -0.12898943  0.01178537]
[ 0.24198086  0.18450749 -0.12900628  0.01178749]
[ 0.24200886  0.18453025 -0.12902312  0.01178962]
[ 0.24203686  0.184553   -0.12903996  0.01179175]
[ 0.24206486  0.18457576 -0.1290568   0.01179388]
[ 0.24209286  0.18459851 -0.12907363  0.011796  ]


[ 0.24687948  0.1884971  -0.13195654  0.01216009]
[ 0.24690714  0.18851968 -0.13197322  0.01216219]
[ 0.2469348   0.18854225 -0.1319899   0.0121643 ]
[ 0.24696246  0.18856483 -0.13200659  0.01216641]
[ 0.24699011  0.18858741 -0.13202327  0.01216851]
[ 0.24701776  0.18860998 -0.13203995  0.01217062]
[ 0.24704542  0.18863255 -0.13205663  0.01217272]
[ 0.24707307  0.18865513 -0.13207331  0.01217483]
[ 0.24710071  0.1886777  -0.13208998  0.01217694]
[ 0.24712836  0.18870027 -0.13210666  0.01217904]
[ 0.247156    0.18872284 -0.13212334  0.01218115]
[ 0.24718365  0.1887454  -0.13214001  0.01218325]
[ 0.24721129  0.18876797 -0.13215669  0.01218536]
[ 0.24723893  0.18879054 -0.13217336  0.01218746]
[ 0.24726656  0.1888131  -0.13219003  0.01218957]
[ 0.2472942   0.18883567 -0.1322067   0.01219167]
[ 0.24732183  0.18885823 -0.13222337  0.01219378]
[ 0.24734946  0.18888079 -0.13224004  0.01219588]
[ 0.24737709  0.18890335 -0.13225671  0.01219799]
[ 0.24740471  0.18892591 -0.13227338  0.01220009]


[ 0.25141758  0.19220887 -0.13469739  0.01250613]
[ 0.25144492  0.19223129 -0.13471393  0.01250822]
[ 0.25147226  0.1922537  -0.13473046  0.01251031]
[ 0.2514996   0.19227611 -0.134747    0.01251239]
[ 0.25152694  0.19229852 -0.13476354  0.01251448]
[ 0.25155428  0.19232093 -0.13478007  0.01251657]
[ 0.25158161  0.19234333 -0.1347966   0.01251866]
[ 0.25160895  0.19236574 -0.13481314  0.01252074]
[ 0.25163628  0.19238814 -0.13482967  0.01252283]
[ 0.25166361  0.19241055 -0.1348462   0.01252492]
[ 0.25169093  0.19243295 -0.13486273  0.012527  ]
[ 0.25171826  0.19245535 -0.13487926  0.01252909]
[ 0.25174558  0.19247775 -0.13489579  0.01253118]
[ 0.2517729   0.19250015 -0.13491231  0.01253326]
[ 0.25180022  0.19252255 -0.13492884  0.01253535]
[ 0.25182754  0.19254495 -0.13494537  0.01253743]
[ 0.25185486  0.19256735 -0.13496189  0.01253952]
[ 0.25188217  0.19258975 -0.13497841  0.01254161]
[ 0.25190948  0.19261214 -0.13499494  0.01254369]
[ 0.25193679  0.19263453 -0.13501146  0.01254578]


[ 0.25611981  0.19607131 -0.1375454   0.0128656 ]
[ 0.25614682  0.19609355 -0.13756179  0.01286767]
[ 0.25617384  0.19611579 -0.13757817  0.01286974]
[ 0.25620085  0.19613803 -0.13759456  0.01287181]
[ 0.25622786  0.19616027 -0.13761094  0.01287387]
[ 0.25625487  0.1961825  -0.13762732  0.01287594]
[ 0.25628187  0.19620474 -0.13764371  0.01287801]
[ 0.25630888  0.19622697 -0.13766009  0.01288008]
[ 0.25633588  0.1962492  -0.13767647  0.01288214]
[ 0.25636288  0.19627144 -0.13769285  0.01288421]
[ 0.25638988  0.19629367 -0.13770922  0.01288628]
[ 0.25641687  0.1963159  -0.1377256   0.01288834]
[ 0.25644387  0.19633812 -0.13774198  0.01289041]
[ 0.25647086  0.19636035 -0.13775836  0.01289248]
[ 0.25649785  0.19638258 -0.13777473  0.01289454]
[ 0.25652484  0.1964048  -0.1377911   0.01289661]
[ 0.25655183  0.19642703 -0.13780748  0.01289868]
[ 0.25657881  0.19644925 -0.13782385  0.01290074]
[ 0.25660579  0.19647148 -0.13784022  0.01290281]
[ 0.25663278  0.1964937  -0.13785659  0.01290487]


[ 0.26081879  0.1999482  -0.14039981  0.01322577]
[ 0.26084548  0.19997026 -0.14041604  0.01322782]
[ 0.26087216  0.19999233 -0.14043228  0.01322987]
[ 0.26089885  0.2000144  -0.14044851  0.01323192]
[ 0.26092553  0.20003646 -0.14046474  0.01323397]
[ 0.26095221  0.20005852 -0.14048098  0.01323601]
[ 0.26097888  0.20008058 -0.14049721  0.01323806]
[ 0.26100556  0.20010265 -0.14051344  0.01324011]
[ 0.26103223  0.20012471 -0.14052966  0.01324216]
[ 0.2610589   0.20014676 -0.14054589  0.0132442 ]
[ 0.26108557  0.20016882 -0.14056212  0.01324625]
[ 0.26111224  0.20019088 -0.14057835  0.0132483 ]
[ 0.2611389   0.20021294 -0.14059457  0.01325034]
[ 0.26116557  0.20023499 -0.14061079  0.01325239]
[ 0.26119223  0.20025704 -0.14062702  0.01325444]
[ 0.26121889  0.2002791  -0.14064324  0.01325648]
[ 0.26124555  0.20030115 -0.14065946  0.01325853]
[ 0.2612722   0.2003232  -0.14067568  0.01326058]
[ 0.26129886  0.20034525 -0.1406919   0.01326262]
[ 0.26132551  0.2003673  -0.14070812  0.01326467]


[ 0.26532863  0.20368552 -0.14314739  0.01357236]
[ 0.265355    0.20370742 -0.14316347  0.01357439]
[ 0.26538137  0.20372932 -0.14317956  0.01357642]
[ 0.26540773  0.20375122 -0.14319565  0.01357845]
[ 0.2654341   0.20377311 -0.14321174  0.01358048]
[ 0.26546046  0.20379501 -0.14322782  0.01358251]
[ 0.26548682  0.20381691 -0.14324391  0.01358453]
[ 0.26551318  0.2038388  -0.14325999  0.01358656]
[ 0.26553954  0.2038607  -0.14327607  0.01358859]
[ 0.26556589  0.20388259 -0.14329216  0.01359062]
[ 0.26559224  0.20390448 -0.14330824  0.01359265]
[ 0.26561859  0.20392637 -0.14332432  0.01359468]
[ 0.26564494  0.20394826 -0.1433404   0.0135967 ]
[ 0.26567129  0.20397015 -0.14335648  0.01359873]
[ 0.26569764  0.20399204 -0.14337255  0.01360076]
[ 0.26572398  0.20401393 -0.14338863  0.01360279]
[ 0.26575032  0.20403581 -0.14340471  0.01360481]
[ 0.26577666  0.2040577  -0.14342078  0.01360684]
[ 0.265803    0.20407958 -0.14343686  0.01360887]
[ 0.26582934  0.20410147 -0.14345293  0.0136109 ]


[ 0.27061784  0.20808983 -0.14638012  0.01398002]
[ 0.27064383  0.20811154 -0.14639603  0.01398202]
[ 0.27066983  0.20813324 -0.14641195  0.01398403]
[ 0.27069582  0.20815495 -0.14642787  0.01398604]
[ 0.27072182  0.20817665 -0.14644378  0.01398804]
[ 0.27074781  0.20819835 -0.1464597   0.01399005]
[ 0.2707738   0.20822005 -0.14647561  0.01399205]
[ 0.27079978  0.20824175 -0.14649152  0.01399406]
[ 0.27082577  0.20826345 -0.14650743  0.01399607]
[ 0.27085175  0.20828515 -0.14652334  0.01399807]
[ 0.27087773  0.20830685 -0.14653926  0.01400008]
[ 0.27090371  0.20832854 -0.14655516  0.01400208]
[ 0.27092969  0.20835024 -0.14657107  0.01400409]
[ 0.27095566  0.20837193 -0.14658698  0.0140061 ]
[ 0.27098164  0.20839363 -0.14660289  0.0140081 ]
[ 0.27100761  0.20841532 -0.14661879  0.01401011]
[ 0.27103358  0.20843701 -0.1466347   0.01401211]
[ 0.27105955  0.2084587  -0.1466506   0.01401412]
[ 0.27108552  0.20848039 -0.14666651  0.01401612]
[ 0.27111148  0.20850208 -0.14668241  0.01401813]


[ 0.27549904  0.21217521 -0.14937365  0.01435738]
[ 0.27552469  0.21219673 -0.14938941  0.01435936]
[ 0.27555035  0.21221826 -0.14940517  0.01436135]
[ 0.275576    0.21223978 -0.14942092  0.01436333]
[ 0.27560165  0.2122613  -0.14943668  0.01436532]
[ 0.27562729  0.21228283 -0.14945244  0.01436731]
[ 0.27565294  0.21230435 -0.14946819  0.01436929]
[ 0.27567858  0.21232587 -0.14948395  0.01437128]
[ 0.27570422  0.21234738 -0.1494997   0.01437326]
[ 0.27572986  0.2123689  -0.14951545  0.01437525]
[ 0.2757555   0.21239042 -0.1495312   0.01437723]
[ 0.27578114  0.21241193 -0.14954696  0.01437922]
[ 0.27580677  0.21243345 -0.14956271  0.0143812 ]
[ 0.2758324   0.21245496 -0.14957845  0.01438319]
[ 0.27585803  0.21247647 -0.1495942   0.01438517]
[ 0.27588366  0.21249799 -0.14960995  0.01438716]
[ 0.27590929  0.2125195  -0.1496257   0.01438914]
[ 0.27593491  0.21254101 -0.14964144  0.01439113]
[ 0.27596054  0.21256252 -0.14965719  0.01439311]
[ 0.27598616  0.21258402 -0.14967293  0.0143951 ]


[ 0.28072047  0.21656809 -0.15258696  0.0147623 ]
[ 0.28074576  0.21658943 -0.15260255  0.01476427]
[ 0.28077104  0.21661076 -0.15261814  0.01476623]
[ 0.28079633  0.21663209 -0.15263373  0.01476819]
[ 0.28082161  0.21665341 -0.15264931  0.01477016]
[ 0.28084689  0.21667474 -0.1526649   0.01477212]
[ 0.28087216  0.21669607 -0.15268049  0.01477408]
[ 0.28089744  0.2167174  -0.15269607  0.01477605]
[ 0.28092271  0.21673872 -0.15271165  0.01477801]
[ 0.28094798  0.21676004 -0.15272724  0.01477997]
[ 0.28097325  0.21678137 -0.15274282  0.01478194]
[ 0.28099852  0.21680269 -0.1527584   0.0147839 ]
[ 0.28102379  0.21682401 -0.15277398  0.01478586]
[ 0.28104905  0.21684533 -0.15278956  0.01478783]
[ 0.28107431  0.21686665 -0.15280514  0.01478979]
[ 0.28109957  0.21688797 -0.15282072  0.01479175]
[ 0.28112483  0.21690929 -0.15283629  0.01479372]
[ 0.28115009  0.2169306  -0.15285187  0.01479568]
[ 0.28117535  0.21695192 -0.15286745  0.01479764]
[ 0.2812006   0.21697324 -0.15288302  0.0147996 ]


[ 0.28536807  0.22049854 -0.15545708  0.01512385]
[ 0.28539303  0.2205197  -0.15547251  0.0151258 ]
[ 0.28541798  0.22054086 -0.15548795  0.01512774]
[ 0.28544293  0.22056202 -0.15550339  0.01512969]
[ 0.28546789  0.22058317 -0.15551882  0.01513163]
[ 0.28549284  0.22060433 -0.15553426  0.01513357]
[ 0.28551779  0.22062548 -0.15554969  0.01513552]
[ 0.28554273  0.22064664 -0.15556513  0.01513746]
[ 0.28556768  0.22066779 -0.15558056  0.01513941]
[ 0.28559262  0.22068894 -0.15559599  0.01514135]
[ 0.28561756  0.22071009 -0.15561142  0.01514329]
[ 0.2856425   0.22073124 -0.15562685  0.01514524]
[ 0.28566744  0.22075239 -0.15564228  0.01514718]
[ 0.28569238  0.22077354 -0.15565771  0.01514912]
[ 0.28571731  0.22079469 -0.15567314  0.01515107]
[ 0.28574224  0.22081583 -0.15568856  0.01515301]
[ 0.28576717  0.22083698 -0.15570399  0.01515495]
[ 0.2857921   0.22085812 -0.15571941  0.01515689]
[ 0.28581703  0.22087927 -0.15573484  0.01515884]
[ 0.28584196  0.22090041 -0.15575026  0.01516078]


[ 0.29015226  0.22456512 -0.15842162  0.01549717]
[ 0.29017688  0.2245861  -0.1584369   0.0154991 ]
[ 0.2902015   0.22460708 -0.15845218  0.01550102]
[ 0.29022611  0.22462806 -0.15846746  0.01550294]
[ 0.29025073  0.22464903 -0.15848274  0.01550487]
[ 0.29027534  0.22467001 -0.15849802  0.01550679]
[ 0.29029995  0.22469099 -0.1585133   0.01550872]
[ 0.29032456  0.22471196 -0.15852858  0.01551064]
[ 0.29034916  0.22473294 -0.15854385  0.01551256]
[ 0.29037377  0.22475391 -0.15855913  0.01551449]
[ 0.29039837  0.22477488 -0.1585744   0.01551641]
[ 0.29042297  0.22479586 -0.15858968  0.01551833]
[ 0.29044757  0.22481683 -0.15860495  0.01552025]
[ 0.29047217  0.2248378  -0.15862022  0.01552218]
[ 0.29049677  0.22485877 -0.15863549  0.0155241 ]
[ 0.29052136  0.22487973 -0.15865076  0.01552602]
[ 0.29054595  0.2249007  -0.15866603  0.01552795]
[ 0.29057054  0.22492167 -0.1586813   0.01552987]
[ 0.29059513  0.22494263 -0.15869657  0.01553179]
[ 0.29061972  0.2249636  -0.15871184  0.01553371]


[ 0.29530834  0.22897186 -0.16162837  0.01590084]
[ 0.29533259  0.22899265 -0.16164348  0.01590275]
[ 0.29535684  0.22901344 -0.1616586   0.01590465]
[ 0.29538109  0.22903423 -0.16167371  0.01590655]
[ 0.29540534  0.22905501 -0.16168882  0.01590845]
[ 0.29542959  0.2290758  -0.16170393  0.01591035]
[ 0.29545383  0.22909658 -0.16171904  0.01591226]
[ 0.29547807  0.22911736 -0.16173415  0.01591416]
[ 0.29550232  0.22913815 -0.16174926  0.01591606]
[ 0.29552655  0.22915893 -0.16176436  0.01591796]
[ 0.29555079  0.22917971 -0.16177947  0.01591986]
[ 0.29557503  0.22920049 -0.16179457  0.01592176]
[ 0.29559926  0.22922127 -0.16180968  0.01592366]
[ 0.29562349  0.22924204 -0.16182478  0.01592556]
[ 0.29564773  0.22926282 -0.16183989  0.01592747]
[ 0.29567195  0.2292836  -0.16185499  0.01592937]
[ 0.29569618  0.22930437 -0.16187009  0.01593127]
[ 0.29572041  0.22932515 -0.16188519  0.01593317]
[ 0.29574463  0.22934592 -0.16190029  0.01593507]
[ 0.29576885  0.22936669 -0.16191539  0.01593697]


[ 0.30002918  0.23302918 -0.16457546  0.01627169]
[ 0.30005309  0.2330498  -0.16459042  0.01627357]
[ 0.30007701  0.23307041 -0.16460538  0.01627546]
[ 0.30010092  0.23309102 -0.16462034  0.01627734]
[ 0.30012484  0.23311163 -0.16463529  0.01627922]
[ 0.30014875  0.23313224 -0.16465025  0.0162811 ]
[ 0.30017266  0.23315284 -0.1646652   0.01628298]
[ 0.30019657  0.23317345 -0.16468016  0.01628486]
[ 0.30022047  0.23319406 -0.16469511  0.01628675]
[ 0.30024437  0.23321466 -0.16471006  0.01628863]
[ 0.30026828  0.23323526 -0.16472501  0.01629051]
[ 0.30029218  0.23325587 -0.16473996  0.01629239]
[ 0.30031608  0.23327647 -0.16475491  0.01629427]
[ 0.30033997  0.23329707 -0.16476986  0.01629615]
[ 0.30036387  0.23331767 -0.16478481  0.01629803]
[ 0.30038776  0.23333827 -0.16479976  0.01629991]
[ 0.30041166  0.23335887 -0.16481471  0.01630179]
[ 0.30043555  0.23337947 -0.16482965  0.01630367]
[ 0.30045944  0.23340006 -0.1648446   0.01630555]
[ 0.30048332  0.23342066 -0.16485954  0.01630743]


[ 0.30529737  0.23758319 -0.16787709  0.01668699]
[ 0.30532091  0.2376036  -0.16789188  0.01668885]
[ 0.30534445  0.23762402 -0.16790666  0.01669071]
[ 0.30536799  0.23764443 -0.16792145  0.01669257]
[ 0.30539153  0.23766484 -0.16793623  0.01669443]
[ 0.30541506  0.23768525 -0.16795101  0.01669629]
[ 0.3054386   0.23770566 -0.1679658   0.01669815]
[ 0.30546213  0.23772607 -0.16798058  0.01670001]
[ 0.30548566  0.23774648 -0.16799536  0.01670187]
[ 0.30550919  0.23776689 -0.16801014  0.01670372]
[ 0.30553272  0.2377873  -0.16802491  0.01670558]
[ 0.30555624  0.2378077  -0.16803969  0.01670744]
[ 0.30557977  0.23782811 -0.16805447  0.0167093 ]
[ 0.30560329  0.23784851 -0.16806925  0.01671116]
[ 0.30562681  0.23786891 -0.16808402  0.01671302]
[ 0.30565033  0.23788932 -0.1680988   0.01671487]
[ 0.30567385  0.23790972 -0.16811357  0.01671673]
[ 0.30569737  0.23793012 -0.16812834  0.01671859]
[ 0.30572088  0.23795052 -0.16814311  0.01672045]
[ 0.30574439  0.23797092 -0.16815789  0.01672231]


[ 0.30981014  0.24150689 -0.17071639  0.017044  ]
[ 0.30983336  0.24152713 -0.17073103  0.01704584]
[ 0.30985658  0.24154737 -0.17074567  0.01704768]
[ 0.3098798   0.24156762 -0.1707603   0.01704952]
[ 0.30990301  0.24158786 -0.17077494  0.01705136]
[ 0.30992623  0.2416081  -0.17078957  0.0170532 ]
[ 0.30994944  0.24162834 -0.1708042   0.01705504]
[ 0.30997265  0.24164858 -0.17081884  0.01705688]
[ 0.30999586  0.24166882 -0.17083347  0.01705872]
[ 0.31001906  0.24168906 -0.1708481   0.01706056]
[ 0.31004227  0.2417093  -0.17086273  0.0170624 ]
[ 0.31006548  0.24172953 -0.17087736  0.01706424]
[ 0.31008868  0.24174977 -0.17089199  0.01706608]
[ 0.31011188  0.24177    -0.17090661  0.01706791]
[ 0.31013508  0.24179024 -0.17092124  0.01706975]
[ 0.31015828  0.24181047 -0.17093587  0.01707159]
[ 0.31018147  0.2418307  -0.17095049  0.01707343]
[ 0.31020467  0.24185093 -0.17096512  0.01707527]
[ 0.31022786  0.24187116 -0.17097974  0.01707711]
[ 0.31025105  0.24189139 -0.17099436  0.01707895]


[ 0.31377981  0.24497621 -0.17322271  0.01735903]
[ 0.31380275  0.2449963  -0.17323722  0.01736086]
[ 0.31382569  0.2450164  -0.17325172  0.01736268]
[ 0.31384862  0.24503649 -0.17326623  0.0173645 ]
[ 0.31387155  0.24505659 -0.17328073  0.01736632]
[ 0.31389448  0.24507668 -0.17329523  0.01736815]
[ 0.31391741  0.24509677 -0.17330974  0.01736997]
[ 0.31394034  0.24511686 -0.17332424  0.01737179]
[ 0.31396326  0.24513695 -0.17333874  0.01737361]
[ 0.31398619  0.24515704 -0.17335324  0.01737544]
[ 0.31400911  0.24517712 -0.17336774  0.01737726]
[ 0.31403203  0.24519721 -0.17338224  0.01737908]
[ 0.31405495  0.2452173  -0.17339673  0.0173809 ]
[ 0.31407787  0.24523738 -0.17341123  0.01738272]
[ 0.31410078  0.24525747 -0.17342573  0.01738455]
[ 0.3141237   0.24527755 -0.17344022  0.01738637]
[ 0.31414661  0.24529763 -0.17345472  0.01738819]
[ 0.31416952  0.24531771 -0.17346921  0.01739001]
[ 0.31419243  0.24533779 -0.1734837   0.01739183]
[ 0.31421534  0.24535787 -0.17349819  0.01739365]


[ 0.31842516  0.24905783 -0.17616628  0.01772889]
[ 0.31844776  0.24907775 -0.17618064  0.0177307 ]
[ 0.31847037  0.24909767 -0.17619499  0.0177325 ]
[ 0.31849297  0.24911759 -0.17620934  0.0177343 ]
[ 0.31851557  0.24913751 -0.17622369  0.01773611]
[ 0.31853817  0.24915743 -0.17623804  0.01773791]
[ 0.31856076  0.24917734 -0.17625239  0.01773971]
[ 0.31858336  0.24919726 -0.17626673  0.01774151]
[ 0.31860595  0.24921717 -0.17628108  0.01774332]
[ 0.31862854  0.24923708 -0.17629543  0.01774512]
[ 0.31865113  0.249257   -0.17630977  0.01774692]
[ 0.31867372  0.24927691 -0.17632412  0.01774872]
[ 0.31869631  0.24929682 -0.17633846  0.01775052]
[ 0.31871889  0.24931673 -0.1763528   0.01775233]
[ 0.31874148  0.24933664 -0.17636715  0.01775413]
[ 0.31876406  0.24935654 -0.17638149  0.01775593]
[ 0.31878664  0.24937645 -0.17639583  0.01775773]
[ 0.31880922  0.24939636 -0.17641017  0.01775953]
[ 0.31883179  0.24941626 -0.17642451  0.01776133]
[ 0.31885437  0.24943617 -0.17643885  0.01776313]


[ 0.32246798  0.25262972 -0.17873767  0.01805187]
[ 0.32249029  0.25264949 -0.17875189  0.01805366]
[ 0.32251261  0.25266925 -0.17876611  0.01805544]
[ 0.32253492  0.25268902 -0.17878033  0.01805723]
[ 0.32255723  0.25270878 -0.17879454  0.01805901]
[ 0.32257954  0.25272855 -0.17880876  0.0180608 ]
[ 0.32260184  0.25274831 -0.17882297  0.01806258]
[ 0.32262415  0.25276807 -0.17883719  0.01806437]
[ 0.32264645  0.25278783 -0.1788514   0.01806615]
[ 0.32266875  0.25280759 -0.17886561  0.01806794]
[ 0.32269105  0.25282735 -0.17887982  0.01806972]
[ 0.32271335  0.25284711 -0.17889403  0.01807151]
[ 0.32273565  0.25286687 -0.17890824  0.01807329]
[ 0.32275794  0.25288662 -0.17892245  0.01807508]
[ 0.32278024  0.25290638 -0.17893666  0.01807686]
[ 0.32280253  0.25292613 -0.17895087  0.01807864]
[ 0.32282482  0.25294589 -0.17896508  0.01808043]
[ 0.32284711  0.25296564 -0.17897928  0.01808221]
[ 0.3228694   0.2529854  -0.17899349  0.018084  ]
[ 0.32289168  0.25300515 -0.17900769  0.01808578]


[ 0.32665708  0.25635072 -0.18141182  0.01838764]
[ 0.3266791   0.25637032 -0.1814259   0.0183894 ]
[ 0.32670111  0.25638993 -0.18143998  0.01839117]
[ 0.32672312  0.25640954 -0.18145406  0.01839294]
[ 0.32674513  0.25642914 -0.18146813  0.01839471]
[ 0.32676714  0.25644875 -0.18148221  0.01839647]
[ 0.32678914  0.25646835 -0.18149628  0.01839824]
[ 0.32681115  0.25648796 -0.18151036  0.01840001]
[ 0.32683315  0.25650756 -0.18152443  0.01840177]
[ 0.32685515  0.25652716 -0.18153851  0.01840354]
[ 0.32687715  0.25654676 -0.18155258  0.01840531]
[ 0.32689915  0.25656636 -0.18156665  0.01840707]
[ 0.32692114  0.25658596 -0.18158072  0.01840884]
[ 0.32694314  0.25660556 -0.18159479  0.01841061]
[ 0.32696513  0.25662515 -0.18160886  0.01841237]
[ 0.32698712  0.25664475 -0.18162293  0.01841414]
[ 0.32700911  0.25666435 -0.181637    0.0184159 ]
[ 0.3270311   0.25668394 -0.18165107  0.01841767]
[ 0.32705309  0.25670353 -0.18166513  0.01841944]
[ 0.32707507  0.25672313 -0.1816792   0.0184212 ]


[ 0.33100671  0.26023632 -0.1841992   0.01873749]
[ 0.33102841  0.26025576 -0.18421314  0.01873924]
[ 0.33105011  0.2602752  -0.18422707  0.01874099]
[ 0.33107181  0.26029464 -0.18424101  0.01874273]
[ 0.33109351  0.26031408 -0.18425494  0.01874448]
[ 0.3311152   0.26033352 -0.18426887  0.01874623]
[ 0.33113689  0.26035296 -0.1842828   0.01874798]
[ 0.33115858  0.2603724  -0.18429673  0.01874973]
[ 0.33118027  0.26039184 -0.18431066  0.01875148]
[ 0.33120196  0.26041127 -0.18432459  0.01875322]
[ 0.33122365  0.26043071 -0.18433852  0.01875497]
[ 0.33124533  0.26045014 -0.18435244  0.01875672]
[ 0.33126701  0.26046958 -0.18436637  0.01875847]
[ 0.3312887   0.26048901 -0.18438029  0.01876021]
[ 0.33131038  0.26050844 -0.18439422  0.01876196]
[ 0.33133206  0.26052787 -0.18440814  0.01876371]
[ 0.33135373  0.2605473  -0.18442207  0.01876546]
[ 0.33137541  0.26056673 -0.18443599  0.0187672 ]
[ 0.33139708  0.26058616 -0.18444991  0.01876895]
[ 0.33141875  0.26060559 -0.18446383  0.0187707 ]


[ 0.33646861  0.26514834 -0.18771541  0.01917862]
[ 0.33648992  0.26516757 -0.18772916  0.01918035]
[ 0.33651123  0.2651868  -0.18774291  0.01918207]
[ 0.33653253  0.26520604 -0.18775666  0.0191838 ]
[ 0.33655383  0.26522527 -0.18777041  0.01918552]
[ 0.33657513  0.2652445  -0.18778416  0.01918725]
[ 0.33659643  0.26526373 -0.18779791  0.01918897]
[ 0.33661773  0.26528296 -0.18781166  0.01919069]
[ 0.33663902  0.26530219 -0.1878254   0.01919242]
[ 0.33666032  0.26532142 -0.18783915  0.01919414]
[ 0.33668161  0.26534064 -0.1878529   0.01919587]
[ 0.3367029   0.26535987 -0.18786664  0.01919759]
[ 0.33672419  0.26537909 -0.18788039  0.01919931]
[ 0.33674548  0.26539832 -0.18789413  0.01920104]
[ 0.33676676  0.26541754 -0.18790787  0.01920276]
[ 0.33678805  0.26543677 -0.18792161  0.01920449]
[ 0.33680933  0.26545599 -0.18793536  0.01920621]
[ 0.33683061  0.26547521 -0.1879491   0.01920793]
[ 0.33685189  0.26549443 -0.18796284  0.01920966]
[ 0.33687317  0.26551365 -0.18797658  0.01921138]


[ 0.34006863  0.26840652 -0.19004306  0.01947052]
[ 0.34008967  0.26842561 -0.19005669  0.01947223]
[ 0.34011072  0.26844471 -0.19007032  0.01947394]
[ 0.34013176  0.26846381 -0.19008395  0.01947565]
[ 0.3401528   0.2684829  -0.19009758  0.01947736]
[ 0.34017384  0.26850199 -0.19011121  0.01947907]
[ 0.34019488  0.26852109 -0.19012484  0.01948077]
[ 0.34021591  0.26854018 -0.19013847  0.01948248]
[ 0.34023695  0.26855927 -0.19015209  0.01948419]
[ 0.34025798  0.26857836 -0.19016572  0.0194859 ]
[ 0.34027901  0.26859745 -0.19017934  0.01948761]
[ 0.34030005  0.26861654 -0.19019297  0.01948932]
[ 0.34032107  0.26863562 -0.19020659  0.01949103]
[ 0.3403421   0.26865471 -0.19022021  0.01949273]
[ 0.34036313  0.2686738  -0.19023384  0.01949444]
[ 0.34038415  0.26869288 -0.19024746  0.01949615]
[ 0.34040518  0.26871197 -0.19026108  0.01949786]
[ 0.3404262   0.26873105 -0.1902747   0.01949956]
[ 0.34044722  0.26875013 -0.19028832  0.01950127]
[ 0.34046824  0.26876922 -0.19030194  0.01950298]


[ 0.34410234  0.27207729 -0.19266094  0.0197987 ]
[ 0.3441231   0.27209624 -0.19267444  0.01980039]
[ 0.34414385  0.27211518 -0.19268793  0.01980208]
[ 0.3441646   0.27213412 -0.19270143  0.01980377]
[ 0.34418535  0.27215306 -0.19271492  0.01980546]
[ 0.3442061   0.272172   -0.19272842  0.01980716]
[ 0.34422684  0.27219093 -0.19274191  0.01980885]
[ 0.34424759  0.27220987 -0.1927554   0.01981054]
[ 0.34426833  0.27222881 -0.19276889  0.01981223]
[ 0.34428907  0.27224774 -0.19278238  0.01981392]
[ 0.34430981  0.27226668 -0.19279587  0.01981561]
[ 0.34433055  0.27228561 -0.19280936  0.0198173 ]
[ 0.34435129  0.27230454 -0.19282285  0.01981899]
[ 0.34437202  0.27232348 -0.19283634  0.01982068]
[ 0.34439276  0.27234241 -0.19284983  0.01982237]
[ 0.34441349  0.27236134 -0.19286331  0.01982406]
[ 0.34443422  0.27238027 -0.1928768   0.01982575]
[ 0.34445495  0.2723992  -0.19289029  0.01982744]
[ 0.34447568  0.27241813 -0.19290377  0.01982913]
[ 0.3444964   0.27243705 -0.19291725  0.01983082]


[ 0.34816183  0.27579354 -0.19530632  0.02013019]
[ 0.34818228  0.27581232 -0.19531968  0.02013187]
[ 0.34820274  0.27583111 -0.19533303  0.02013354]
[ 0.3482232   0.27584989 -0.19534639  0.02013521]
[ 0.34824365  0.27586868 -0.19535975  0.02013689]
[ 0.3482641   0.27588746 -0.19537311  0.02013856]
[ 0.34828456  0.27590624 -0.19538646  0.02014023]
[ 0.34830501  0.27592502 -0.19539982  0.02014191]
[ 0.34832545  0.2759438  -0.19541318  0.02014358]
[ 0.3483459   0.27596258 -0.19542653  0.02014525]
[ 0.34836635  0.27598136 -0.19543988  0.02014693]
[ 0.34838679  0.27600014 -0.19545324  0.0201486 ]
[ 0.34840723  0.27601892 -0.19546659  0.02015027]
[ 0.34842767  0.27603769 -0.19547994  0.02015195]
[ 0.34844811  0.27605647 -0.19549329  0.02015362]
[ 0.34846855  0.27607524 -0.19550664  0.02015529]
[ 0.34848899  0.27609402 -0.19551999  0.02015696]
[ 0.34850942  0.27611279 -0.19553334  0.02015864]
[ 0.34852985  0.27613156 -0.19554669  0.02016031]
[ 0.34855029  0.27615034 -0.19556004  0.02016198]


[ 0.35294902  0.28020528 -0.19844023  0.02052274]
[ 0.35296913  0.28022388 -0.19845343  0.02052439]
[ 0.35298924  0.28024248 -0.19846663  0.02052604]
[ 0.35300934  0.28026108 -0.19847983  0.02052769]
[ 0.35302945  0.28027968 -0.19849302  0.02052935]
[ 0.35304955  0.28029827 -0.19850622  0.020531  ]
[ 0.35306966  0.28031687 -0.19851941  0.02053265]
[ 0.35308976  0.28033547 -0.19853261  0.0205343 ]
[ 0.35310986  0.28035406 -0.1985458   0.02053596]
[ 0.35312996  0.28037266 -0.198559    0.02053761]
[ 0.35315005  0.28039125 -0.19857219  0.02053926]
[ 0.35317015  0.28040985 -0.19858538  0.02054091]
[ 0.35319024  0.28042844 -0.19859857  0.02054256]
[ 0.35321034  0.28044703 -0.19861176  0.02054421]
[ 0.35323043  0.28046562 -0.19862495  0.02054587]
[ 0.35325052  0.28048421 -0.19863814  0.02054752]
[ 0.3532706   0.2805028  -0.19865133  0.02054917]
[ 0.35329069  0.28052139 -0.19866452  0.02055082]
[ 0.35331078  0.28053998 -0.1986777   0.02055247]
[ 0.35333086  0.28055857 -0.19869089  0.02055412]


[ 0.35936887  0.28617337 -0.20266827  0.02105202]
[ 0.35938851  0.28619172 -0.20268125  0.02105365]
[ 0.35940815  0.28621007 -0.20269423  0.02105527]
[ 0.35942779  0.28622842 -0.20270721  0.0210569 ]
[ 0.35944742  0.28624677 -0.20272019  0.02105852]
[ 0.35946706  0.28626512 -0.20273317  0.02106014]
[ 0.35948669  0.28628347 -0.20274614  0.02106177]
[ 0.35950633  0.28630182 -0.20275912  0.02106339]
[ 0.35952596  0.28632017 -0.2027721   0.02106502]
[ 0.35954559  0.28633852 -0.20278507  0.02106664]
[ 0.35956522  0.28635686 -0.20279805  0.02106826]
[ 0.35958484  0.28637521 -0.20281102  0.02106989]
[ 0.35960447  0.28639355 -0.202824    0.02107151]
[ 0.35962409  0.2864119  -0.20283697  0.02107313]
[ 0.35964371  0.28643024 -0.20284994  0.02107476]
[ 0.35966334  0.28644858 -0.20286292  0.02107638]
[ 0.35968296  0.28646692 -0.20287589  0.021078  ]
[ 0.35970257  0.28648526 -0.20288886  0.02107963]
[ 0.35972219  0.2865036  -0.20290183  0.02108125]
[ 0.35974181  0.28652194 -0.2029148   0.02108287]


[ 0.36423471  0.29073797 -0.20589297  0.02145547]
[ 0.36425399  0.29075613 -0.20590579  0.02145707]
[ 0.36427327  0.2907743  -0.20591861  0.02145867]
[ 0.36429256  0.29079246 -0.20593142  0.02146028]
[ 0.36431184  0.29081062 -0.20594423  0.02146188]
[ 0.36433112  0.29082878 -0.20595705  0.02146348]
[ 0.36435039  0.29084694 -0.20596986  0.02146509]
[ 0.36436967  0.2908651  -0.20598267  0.02146669]
[ 0.36438894  0.29088326 -0.20599548  0.02146829]
[ 0.36440822  0.29090142 -0.2060083   0.02146989]
[ 0.36442749  0.29091957 -0.20602111  0.0214715 ]
[ 0.36444676  0.29093773 -0.20603391  0.0214731 ]
[ 0.36446603  0.29095589 -0.20604672  0.0214747 ]
[ 0.3644853   0.29097404 -0.20605953  0.0214763 ]
[ 0.36450456  0.29099219 -0.20607234  0.0214779 ]
[ 0.36452383  0.29101035 -0.20608515  0.02147951]
[ 0.36454309  0.2910285  -0.20609795  0.02148111]
[ 0.36456236  0.29104665 -0.20611076  0.02148271]
[ 0.36458162  0.2910648  -0.20612356  0.02148431]
[ 0.36460088  0.29108295 -0.20613637  0.02148591]


[ 0.36735952  0.29368877 -0.20797337  0.02171564]
[ 0.36737857  0.29370681 -0.20798608  0.02171723]
[ 0.36739763  0.29372485 -0.20799879  0.02171882]
[ 0.36741668  0.2937429  -0.20801149  0.02172041]
[ 0.36743573  0.29376094 -0.2080242   0.02172199]
[ 0.36745478  0.29377897 -0.20803691  0.02172358]
[ 0.36747383  0.29379701 -0.20804962  0.02172517]
[ 0.36749288  0.29381505 -0.20806232  0.02172676]
[ 0.36751192  0.29383309 -0.20807503  0.02172835]
[ 0.36753097  0.29385112 -0.20808773  0.02172994]
[ 0.36755001  0.29386916 -0.20810043  0.02173153]
[ 0.36756905  0.29388719 -0.20811314  0.02173311]
[ 0.36758809  0.29390523 -0.20812584  0.0217347 ]
[ 0.36760713  0.29392326 -0.20813854  0.02173629]
[ 0.36762617  0.29394129 -0.20815124  0.02173788]
[ 0.3676452   0.29395932 -0.20816394  0.02173947]
[ 0.36766424  0.29397735 -0.20817664  0.02174105]
[ 0.36768327  0.29399538 -0.20818934  0.02174264]
[ 0.3677023   0.29401341 -0.20820204  0.02174423]
[ 0.36772133  0.29403144 -0.20821474  0.02174582]


[ 0.37067296  0.29683482 -0.21018771  0.02199246]
[ 0.37069177  0.29685273 -0.21020031  0.02199403]
[ 0.37071058  0.29687064 -0.21021291  0.02199561]
[ 0.37072939  0.29688855 -0.2102255   0.02199718]
[ 0.3707482   0.29690646 -0.2102381   0.02199876]
[ 0.370767    0.29692437 -0.21025069  0.02200033]
[ 0.37078581  0.29694228 -0.21026328  0.02200191]
[ 0.37080461  0.29696019 -0.21027588  0.02200348]
[ 0.37082341  0.2969781  -0.21028847  0.02200505]
[ 0.37084221  0.296996   -0.21030106  0.02200663]
[ 0.37086101  0.29701391 -0.21031365  0.0220082 ]
[ 0.37087981  0.29703181 -0.21032624  0.02200977]
[ 0.37089861  0.29704972 -0.21033883  0.02201135]
[ 0.3709174   0.29706762 -0.21035142  0.02201292]
[ 0.37093619  0.29708552 -0.21036401  0.0220145 ]
[ 0.37095499  0.29710343 -0.2103766   0.02201607]
[ 0.37097378  0.29712133 -0.21038918  0.02201764]
[ 0.37099257  0.29713923 -0.21040177  0.02201921]
[ 0.37101135  0.29715713 -0.21041436  0.02202079]
[ 0.37103014  0.29717503 -0.21042694  0.02202236]


[ 0.37435219  0.3003494  -0.2126569   0.02230102]
[ 0.37437073  0.30036717 -0.21266937  0.02230258]
[ 0.37438927  0.30038494 -0.21268184  0.02230414]
[ 0.37440781  0.30040271 -0.21269431  0.02230569]
[ 0.37442634  0.30042047 -0.21270677  0.02230725]
[ 0.37444488  0.30043824 -0.21271924  0.02230881]
[ 0.37446341  0.300456   -0.21273171  0.02231037]
[ 0.37448194  0.30047377 -0.21274418  0.02231192]
[ 0.37450048  0.30049153 -0.21275664  0.02231348]
[ 0.374519    0.30050929 -0.21276911  0.02231504]
[ 0.37453753  0.30052705 -0.21278157  0.0223166 ]
[ 0.37455606  0.30054482 -0.21279404  0.02231815]
[ 0.37457458  0.30056258 -0.2128065   0.02231971]
[ 0.37459311  0.30058034 -0.21281897  0.02232127]
[ 0.37461163  0.30059809 -0.21283143  0.02232283]
[ 0.37463015  0.30061585 -0.21284389  0.02232438]
[ 0.37464867  0.30063361 -0.21285635  0.02232594]
[ 0.37466719  0.30065137 -0.21286881  0.0223275 ]
[ 0.37468571  0.30066912 -0.21288127  0.02232905]
[ 0.37470422  0.30068688 -0.21289373  0.02233061]


[ 0.37792347  0.30378287 -0.21506439  0.02260175]
[ 0.37794175  0.3038005  -0.21507673  0.02260329]
[ 0.37796002  0.30381813 -0.21508908  0.02260483]
[ 0.3779783   0.30383575 -0.21510143  0.02260637]
[ 0.37799657  0.30385338 -0.21511377  0.02260791]
[ 0.37801484  0.303871   -0.21512612  0.02260946]


KeyboardInterrupt: 